version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - reddocker
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb

    environment:
      MONGO_INITDB_DATABASE: login
      MONGO_INITDB_ROOT_USERNAME: LuisaGiron
      MONGO_INITDB_ROOT_PASSWORD: LuisaGiron1234

networks:
  reddocker:
    driver: bridge

volumes:
  mongodb:
  mongodb_config: